"""Export uv.lock to a marker-free requirements file for `cog build`.

Cog cannot consume a universal `uv export`. Its `pythonPackageForArch` matches
each line against `([a-zA-Z0-9\\-_]+)==([^ ]+)` and rebuilds it as
`name + "==" + version`; `[^ ]+` stops at the space before `;`, so environment
markers are dropped silently. A marker-split pin like

    numpy==2.2.6 ; python_full_version < '3.11'
    numpy==2.4.1 ; python_full_version >= '3.11'

therefore reaches pip as two conflicting pins and the build dies with
ResolutionImpossible. (Still true as of Cog 0.21.0.)

The fix is to evaluate markers here, for the single environment the image
actually has, and emit a file with no markers left in it. Versions still come
straight from uv.lock -- nothing is re-resolved.

Usage:
    python script/export_cog_requirements.py            # rewrite the file
    python script/export_cog_requirements.py --check    # fail if it has drifted
"""

from __future__ import annotations

import argparse
import difflib
import subprocess
import sys
from pathlib import Path

from packaging.requirements import Requirement

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "requirements-cog.txt"

UV_EXPORT = [
    "uv",
    "export",
    "--locked",
    "--no-dev",
    "--no-hashes",
    "--no-emit-project",
    "--format",
    "requirements-txt",
]

# The one environment the Cog image runs: CPython 3.12 on linux/x86_64, per
# `python_version` in cog.yaml and the base image Cog selects for it.
TARGET_ENV = {
    "implementation_name": "cpython",
    "os_name": "posix",
    "platform_machine": "x86_64",
    "platform_python_implementation": "CPython",
    "platform_system": "Linux",
    "python_full_version": "3.12.11",
    "python_version": "3.12",
    "sys_platform": "linux",
}

HEADER = f"""\
# Generated by script/export_cog_requirements.py from uv.lock -- do not edit.
# Regenerate with: python script/export_cog_requirements.py
#
# This is `{" ".join(UV_EXPORT)}`
# with environment markers pre-evaluated for the Cog image
# (CPython {TARGET_ENV["python_full_version"]}, {TARGET_ENV["sys_platform"]}/{TARGET_ENV["platform_machine"]}). Cog drops markers when it
# rewrites requirement lines, which turns marker-split pins into conflicting
# duplicates, so they have to be resolved before it sees them.
"""


def export_lines() -> list[str]:
    result = subprocess.run(
        UV_EXPORT, cwd=REPO_ROOT, capture_output=True, text=True, check=True
    )
    return result.stdout.splitlines()


def render(lines: list[str]) -> str:
    out: list[str] = [HEADER]
    seen: dict[str, str] = {}

    for line in lines:
        stripped = line.strip()
        # uv's own preamble and the `# via ...` provenance comments; the header
        # above replaces them.
        if not stripped or stripped.startswith("#"):
            continue
        # pip options (--index-url, --find-links, ...) pass through untouched.
        if stripped.startswith("-"):
            out.append(stripped)
            continue

        req = Requirement(stripped)
        if req.marker is not None and not req.marker.evaluate(TARGET_ENV):
            continue

        extras = f"[{','.join(sorted(req.extras))}]" if req.extras else ""
        rendered = f"{req.name}{extras}{req.specifier}"

        # Cog would collapse a surviving duplicate into two conflicting pins,
        # which is the exact failure this script exists to prevent -- so refuse
        # to emit one rather than ship a file that cannot build.
        key = req.name.lower()
        if key in seen:
            raise SystemExit(
                f"error: {req.name} resolves to two requirements for the target "
                f"environment: {seen[key]!r} and {rendered!r}. Markers in uv.lock "
                f"do not partition cleanly for CPython "
                f"{TARGET_ENV['python_full_version']} on "
                f"{TARGET_ENV['sys_platform']}/{TARGET_ENV['platform_machine']}."
            )
        seen[key] = rendered
        out.append(rendered)

    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the committed file differs from a fresh export",
    )
    args = parser.parse_args()

    content = render(export_lines())

    if not args.check:
        OUTPUT.write_text(content)
        print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")
        return 0

    current = OUTPUT.read_text() if OUTPUT.exists() else ""
    if current == content:
        print(f"{OUTPUT.relative_to(REPO_ROOT)} is up to date")
        return 0

    name = str(OUTPUT.relative_to(REPO_ROOT))
    sys.stdout.writelines(
        difflib.unified_diff(
            current.splitlines(keepends=True),
            content.splitlines(keepends=True),
            fromfile=f"{name} (committed)",
            tofile=f"{name} (expected)",
        )
    )
    print(
        f"\nerror: {name} is out of date. "
        f"Run: python script/export_cog_requirements.py",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
